apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: LoadBalancer # Use LoadBalancer for external access (or ClusterIP for internal)
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80 # Port to expose outside of the cluster
      targetPort: 3000 # Port on the container running your app
